### ISSUE TITLE
No install location for pango

### ISSUE THREAD

**Issue by alexis-diavatis** [mattn/go-gtk#139]
cd go-gtk
make install

outputs: 

cd pango && go install -x
go install: no install location for _/home/alex/Git/go-gtk/pango
make: *** [install] Error 1

I have Go 1.0.3

**Comment by ljgww** [comment]
ubunty 14.4 pango problem resolved by putting source into .../go/src/ (more precise merging into existing /go/src dir eg: ~/go/src where GOROOT=~/go)

**Comment by alexis-diavatis** [comment]
@corebob Oh right, I forgot my noob question! I'm writing Go almost everyday now! Thanks for telling though ;-)

**Comment by corebob** [comment]
@alexis-diavatis 
No problem
