### ISSUE TITLE
How to install go-gtk in win8?

### ISSUE THREAD

**Issue by asdtgb** [mattn/go-gtk#200]
sorry for being newbie. please make it step by step thank you

**Comment by joeyroosing** [comment]
Any plans to update to gtk3 in the future?

**Comment by mattn** [comment]
gtk3 already exists on https://github.com/conformal/gotk3. I wonder why you want.

**Comment by joeyroosing** [comment]
Thanks for the provided link. As to why, I prefer the latest and greatest, if that makes sense
