### ISSUE TITLE
can not run the demo

### ISSUE THREAD

**Issue by catric** [mattn/go-gtk#219]
Thanks for your contribution. 
I am new to the go language, and I followed your tips to set up the environment for go-gtk, at last, it seemed I succeeded,  some of the example programs in the "example" dir could be run well, such as "table", "toolbar", but some other examples would go wrong, 
when I ran the demo, it return error ".\demo.go:329: undefined: gdkpixbuf.NewFromFile"
when I ran the "listview", the program would crash.

The OS for testing is win7 64bit , I installed mingw 32bit, gtk and related files in 32bit version

could you please check the issues ? thanks!

**Comment by timkofu** [comment]
I just ran into this same problem just now:

`# command-line-arguments`
`./calc.go:329: undefined: gdkpixbuf.NewFromFile`

I'm on Ubuntu 16.04 64 bit, Go version 1.6.2

`go get github.com/mattn/go-gtk/gtk` ran without errors.

**Comment by REPTILEHAUS** [comment]
Also hitting this error on OSX El Capitan

# command-line-arguments
./gtk.go:328: undefined: gdkpixbuf.NewFromFile

**Comment by mattn** [comment]
Maybe you install gtk3 not gtk2?

**Comment by REPTILEHAUS** [comment]
I used go get github.com/mattn/go-gtk/gtk ? not sure what version it is


Kind Regards,


Paddy


PATRICK O'SULLIVAN

Developer | SysAdmin
Linkedin:  linkedin.com/in/paddyjosullivan
<http://ie.linkedin.com/in/paddyjosullivan/>
Email:     paddy.osullivan@r <padjo.osullivan@gmail.com>eptileha.us
Keybase:   keybase.io/reptilehaus
​Slack
:
​
reptilehaus.slack.com
Web:    www.reptilehaus.io ** Coming Soon **
Phone:     +353 86 024 2110

Twitter:   @REPTILE_HAUS <https://twitter.com/reptile_haus>
Facebook:  REPTILEHAUS <https://www.facebook.com/reptilehausagency/>

**Comment by mattn** [comment]
go-gtk is depend on GTK2 library. Try to check whether gtk2 is installed

```
$ pkg-config --cflags gtk+-2.0
```

**Comment by REPTILEHAUS** [comment]
I ran that and here is the output:

-D_REENTRANT -I/usr/local/Cellar/gtk+/2.24.30/include/gtk-2.0 -I/usr/local/Cellar/gtk+/2.24.30/lib/gtk-2.0/include -I/usr/local/Cellar/pango/1.38.1/include/pango-1.0 -I/usr/local/Cellar/harfbuzz/1.2.4/include/harfbuzz -I/usr/local/Cellar/pango/1.38.1/include/pango-1.0 -I/usr/local/Cellar/atk/2.18.0_1/include/atk-1.0 -I/usr/local/Cellar/cairo/1.14.6_1/include/cairo -I/usr/local/Cellar/pixman/0.34.0/include/pixman-1 -I/usr/local/Cellar/fontconfig/2.11.1_2/include -I/usr/local/Cellar/freetype/2.6.3/include/freetype2 -I/usr/local/Cellar/libpng/1.6.21/include/libpng16 -I/usr/local/Cellar/gdk-pixbuf/2.32.3/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/libpng/1.6.21/include/libpng16 -I/usr/local/Cellar/glib/2.46.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.46.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include
Paddys-MBP:project-a pad

**Comment by mattn** [comment]
Could you please try to grep `gdk_pixbuf_new_from_file` in your directories of include(s)?
