### ISSUE TITLE
Run .exe problem

### ISSUE THREAD

**Issue by LittleBuster** [mattn/go-gtk#236]
After a successful building on Windows (MinGW), I try run .exe and have this error:

C:\go-path\src\github.com\mattn\go-gtk\example\demo>demo.exe
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x546c10]

runtime stack:
invalid spdelta 0x546bf0 0x546c10 0x1185af -1
runtime.gothrow(0x647dc8, 0x2a)
        c:/go/src/runtime/panic.go:503 +0x67
runtime.sigpanic()
        c:/go/src/runtime/os_windows.go:36 +0x53
invalid spdelta 0x546bf0 0x546c10 0x1185af -1
_cgo_73cb713ea330_Cfunc__g_signal_connect()
        ?:0 +0x20
goroutine 1 [syscall, locked to thread]:
runtime.cgocall_errno(0x546bf0, 0x11cdbd1c, 0x0)
        c:/go/src/runtime/cgocall.go:130 +0xbc fp=0x11cdbd0c sp=0x11cdbcf4
github.com/mattn/go-gtk/glib._Cfunc__g_signal_connect(0x0, 0x1978b10, 0x6, 0x0)
        C:/go-path/src/github.com/mattn/go-gtk/glib/:78 +0x3f fp=0x11cdbd1c sp=0
x11cdbd0c
github.com/mattn/go-gtk/glib.(*GObject).Connect(0x11cdc2c8, 0x5f80c8, 0x7, 0x56b
3c0, 0x11cdc2c0, 0x0, 0x0, 0x0, 0x0)
        C:/go-path/src/github.com/mattn/go-gtk/glib/glib.go:725 +0x22d fp=0x11cd
bd9c sp=0x11cdbd1c
github.com/mattn/go-gtk/gtk.(*Widget).Connect(0x11cdc2b8, 0x5f80c8, 0x7, 0x56b3c
0, 0x11cdc2c0, 0x0, 0x0, 0x0, 0x5)
        C:/go-path/src/github.com/mattn/go-gtk/gtk/gtk.go:9307 +0x94 fp=0x11cdbd
cc sp=0x11cdbd9c
main.main()
        C:/go-path/src/github.com/mattn/go-gtk/example/demo/demo.go:234 +0x1194
fp=0x11cdbfcc sp=0x11cdbdcc
runtime.main()
        c:/go/src/runtime/proc.go:63 +0xcc fp=0x11cdbff0 sp=0x11cdbfcc
runtime.goexit()
        c:/go/src/runtime/asm_386.s:2287 +0x1 fp=0x11cdbff4 sp=0x11cdbff0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_386.s:2287 +0x1

**Comment by mattn** [comment]
32bit/32bit, which arch do you use?

**Comment by LittleBuster** [comment]
32bit win XP

**Comment by mattn** [comment]
what version of gcc do you use?

**Comment by LittleBuster** [comment]
gcc 4.8.1

**Comment by LittleBuster** [comment]
Thank you! I successfully compiled and launched app with gcc 4.9.1
