### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by lukexue** [mattn/go-gtk#237]
ubuntu 15.04 / go version go1.4.2 linux/amd64
---
go get github.com/mattn/go-gtk/gtk

#github.com/mattn/go-gtk/pango
cc1: error: invalid option '64'
#github.com/mattn/go-gtk/glib
cc1: error: invalid option '64'
---
Linux ThinkPad-T420s 4.0.4-040004-lowlatency #201505171336 SMP PREEMPT Sun May 17 17:45:56 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mattn** [comment]
what version of gcc do you use?

**Comment by lukexue** [comment]
gcc version 3.4.5

**Comment by lukexue** [comment]
ok ,i found the reason.  thanks
