### ISSUE TITLE
In windows_64 make fail , I hope get help, thanks

### ISSUE THREAD

**Issue by czxichen** [mattn/go-gtk#240]
This my error info. 
D:\Go\src\go-gtk>make
cd pango && go get -x
WORK=C:\Users\czxichenAppData\Local\Temp\go-build213470251
mkdir -p $WORK\go-gtk\pango\_obj\
mkdir -p $WORK\go-gtk\
cd D:\Go\src\go-gtk\pango
pkg-config --cflags pango
pkg-config --libs pango
CGO_LDFLAGS="-g" "-O2" "-Ld:/Program\\" "Files/gtk/lib" "-lpango-1.0" "-lm" "-lg
object-2.0" "-lglib-2.0" "-lintl" "D:\\Go\\pkg\\tool\\windows_amd64\\cgo.exe" -o
bjdir "C:\\Users\\dijl\\AppData\\Local\\Temp\\go-build213470251\\go-gtk\\pango\\
_obj\\" -- -mms-bitfields "-Id:/Program\\" Files/gtk/include/pango-1.0 "-Id:/Pro
gram\\" Files/gtk/include/glib-2.0 "-Id:/Program\\" Files/gtk/lib/glib-2.0/inclu
de -I "C:\\Users\\dijl\\AppData\\Local\\Temp\\go-build213470251\\go-gtk\\pango\\
_obj\\" pango.go
# go-gtk/pango
gcc: error: Files/gtk/include/pango-1.0: No such file or directory
gcc: error: Files/gtk/include/glib-2.0: No such file or directory
gcc: error: Files/gtk/lib/glib-2.0/include: No such file or directory
makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

I get gtk_dev ,but i don't know use , gtk_dev path : 'D:\gcc\gtk_dev'

**Comment by mattn** [comment]
What output of `pkg-config --cflags --libs gtk-2.0` ?

**Comment by czxichen** [comment]
C:\Users\czxichen>pkg-config --cflags --libs gtk+-3.0
-mms-bitfields -ID:/Program\ Files/gtk/include/gtk-3.0 -ID:/Program\ Files/gtk/i
nclude/cairo -ID:/Program\ Files/gtk/include/pango-1.0 -ID:/Program\ Files/gtk/i
nclude/atk-1.0 -ID:/Program\ Files/gtk/include/cairo -ID:/Program\ Files/gtk/inc
lude/pixman-1 -ID:/Program\ Files/gtk/include -ID:/Program\ Files/gtk/include/fr
eetype2 -ID:/Program\ Files/gtk/include -ID:/Program\ Files/gtk/include/libpng15
 -ID:/Program\ Files/gtk/include/gdk-pixbuf-2.0 -ID:/Program\ Files/gtk/include/
libpng15 -ID:/Program\ Files/gtk/include/glib-2.0 -ID:/Program\ Files/gtk/lib/gl
ib-2.0/include -LD:/Program\ Files/gtk/lib -lgtk-3 -lgdk-3 -lgdi32 -limm32 -lshe
ll32 -lole32 -Wl,-luuid -lpangocairo-1.0 -lpangoft2-1.0 -lfreetype -lfontconfig
-lpangowin32-1.0 -lgdi32 -lpango-1.0 -lm -latk-1.0 -lcairo-gobject -lcairo -lgdk
_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl

**Comment by mattn** [comment]
Could you please show me your `gtk+-2.0.pc` ? it is at your `D:\Program Files\gtk\lib\pkg-config\gtk+-2.0.pc` maybe.

**Comment by czxichen** [comment]
In D:\Program Files\gtk\lib\pkgconfig no file gtk+-2.0.pc,
In D:\Program Files\gtk\lib\pkgconfig Only this file  gtk+-3.0.pc

**Comment by mattn** [comment]
go-gtk is binding for gtk+-2.0 not 3.0

**Comment by czxichen** [comment]
Ok I am try ,thank you

**Comment by czxichen** [comment]
Hi !
D:\Go\src\go-gtk>pkg-config --cflags --libs gtk+-2.0
Files/gtk.2.0/include/gtk-2.0 -mms-bitfields Files/gtk.2.0/lib/gtk-2.0/include F
iles/gtk.2.0/include/atk-1.0 Files/gtk.2.0/include/cairo Files/gtk.2.0/include/p
ango-1.0 Files/gtk.2.0/include/glib-2.0 Files/gtk.2.0/lib/glib-2.0/include Files
/gtk.2.0/include/freetype2 Files/gtk.2.0/include Files/gtk.2.0/include/libpng14
-ID:/Program  Files/gtk.2.0/lib -LD:/Program -lgtk-win32-2.0 -lgdk-win32-2.0 -la
tk-1.0 -lgio-2.0 -lgdk_pixbuf-2.0 -lpangowin32-1.0 -lgdi32 -lpangocairo-1.0 -lpa
ngo-1.0 -lcairo -lgobject-2.0 -lgmodule-2.0 -lglib-2.0 -lintl

D:\Go\src\go-gtk>make
cd pango && go get -x
WORK=C:\Users\dijl\AppData\Local\Temp\go-build045680847
mkdir -p $WORK\go-gtk\pango\_obj\
mkdir -p $WORK\go-gtk\
cd D:\Go\src\go-gtk\pango
pkg-config --cflags pango
pkg-config --libs pango
CGO_LDFLAGS="-g" "-O2" "Files/gtk.2.0/lib" "-Ld:/Program" "-lpango-1.0" "-lgobje
ct-2.0" "-lgmodule-2.0" "-lglib-2.0" "-lintl" "D:\\Go\\pkg\\tool\\windows_amd64\
\cgo.exe" -objdir "C:\\Users\\dijl\\AppData\\Local\\Temp\\go-build045680847\\go-
gtk\\pango\\_obj\\" -- Files/gtk.2.0/include/pango-1.0 Files/gtk.2.0/include/gli
b-2.0 Files/gtk.2.0/lib/glib-2.0/include -mms-bitfields -Id:/Program -I "C:\\Use
rs\\dijl\\AppData\\Local\\Temp\\go-build045680847\\go-gtk\\pango\\_obj\\" pango.
go
# go-gtk/pango
gcc: error: Files/gtk.2.0/include/pango-1.0: No such file or directory
gcc: error: Files/gtk.2.0/include/glib-2.0: No such file or directory
gcc: error: Files/gtk.2.0/lib/glib-2.0/include: No such file or directory
makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mattn** [comment]
Probably, you have `gtk+-2.0.pc` on your `D:\Program Files\gtk.2.0`. please find it and please show me it.

**Comment by czxichen** [comment]
prefix=c:/devel/target/f559a2bf8c482af5f780800010446dc9
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
target=win32

gtk_binary_version=2.10.0
gtk_host=x86_64-w64-mingw32

Name: GTK+
Description: GTK+ Graphical UI Library (${target} target)
Version: 2.16.6
Requires: gdk-${target}-2.0 atk cairo gio-2.0
Libs: -L${libdir} -lgtk-${target}-2.0 
Cflags: -I${includedir}/gtk-2.0 -mms-bitfields

**Comment by mattn** [comment]
probably, you can fix with below's change. note that please do it after backup
before
```
libdir=${exec_prefix}/lib
includedir=${prefix}/include
```
after
```
libdir="${exec_prefix}/lib"
includedir="${prefix}/include"
```

**Comment by czxichen** [comment]
Still have mistakes：
------------------------
gtk+-2.0.pc file:
prefix=c:/devel/target/f559a2bf8c482af5f780800010446dc9
exec_prefix=${prefix}
libdir="${exec_prefix}/lib"
includedir="${prefix}/include"
target=win32

gtk_binary_version=2.10.0
gtk_host=x86_64-w64-mingw32

Name: GTK+
Description: GTK+ Graphical UI Library (${target} target)
Version: 2.16.6
Requires: gdk-${target}-2.0 atk cairo gio-2.0
Libs: -L${libdir} -lgtk-${target}-2.0 
Cflags: -I${includedir}/gtk-2.0 -mms-bitfields

-----------------------
error info.
D:\Go\src\go-gtk>make
cd pango && go get -x
WORK=C:\Users\dijl\AppData\Local\Temp\go-build182623943
mkdir -p $WORK\go-gtk\pango\_obj\
mkdir -p $WORK\go-gtk\
cd D:\Go\src\go-gtk\pango
pkg-config --cflags pango
pkg-config --libs pango
CGO_LDFLAGS="-g" "-O2" "Files/gtk.2.0/lib" "-Ld:/Program" "-lpango-1.0" "-lgobje
ct-2.0" "-lgmodule-2.0" "-lglib-2.0" "-lintl" "D:\\Go\\pkg\\tool\\windows_amd64\
\cgo.exe" -objdir "C:\\Users\\dijl\\AppData\\Local\\Temp\\go-build182623943\\go-
gtk\\pango\\_obj\\" -- Files/gtk.2.0/include/pango-1.0 Files/gtk.2.0/include/gli
b-2.0 Files/gtk.2.0/lib/glib-2.0/include -mms-bitfields -Id:/Program -I "C:\\Use
rs\\dijl\\AppData\\Local\\Temp\\go-build182623943\\go-gtk\\pango\\_obj\\" pango.
go
# go-gtk/pango
gcc: error: Files/gtk.2.0/include/pango-1.0: No such file or directory
gcc: error: Files/gtk.2.0/include/glib-2.0: No such file or directory
gcc: error: Files/gtk.2.0/lib/glib-2.0/include: No such file or directory
makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mattn** [comment]
now what output of `pkg-config --cflags --libs gtk+-2.0` ?

**Comment by mattn** [comment]
Probably you will solve this problem with move the gtk.2.0 directory into non-space-contained-directory.

**Comment by czxichen** [comment]
C:\Users\czxichen>pkg-config --cflags --libs gtk+-2.0
-mms-bitfields Files/gtk.2.0/include/gtk-2.0 Files/gtk.2.0/lib/gtk-2.0/include F
iles/gtk.2.0/include/atk-1.0 Files/gtk.2.0/include/cairo Files/gtk.2.0/include/p
ango-1.0 Files/gtk.2.0/include/glib-2.0 Files/gtk.2.0/lib/glib-2.0/include Files
/gtk.2.0/include/freetype2 Files/gtk.2.0/include Files/gtk.2.0/include/libpng14
-ID:/Program  Files/gtk.2.0/lib -LD:/Program -lgtk-win32-2.0 -lgdk-win32-2.0 -la
tk-1.0 -lgio-2.0 -lgdk_pixbuf-2.0 -lpangowin32-1.0 -lgdi32 -lpangocairo-1.0 -lpa
ngo-1.0 -lcairo -lgobject-2.0 -lgmodule-2.0 -lglib-2.0 -lintl

**Comment by czxichen** [comment]
I try gtk.2.0 move into D:\
now a new problem 
C:\Users\czxichen\AppData\Local\Temp\go-build527426047\go-gtk\pango\_obj\pango.cgo2.
o: In function `_cgo_61e3b251eb97_Cfunc_pango_layout_set_width':
D:/Go/src/go-gtk/pango/pango.go:122: undefined reference to `pango_layout_set_wi
dth'
collect2.exe: error: ld returned 1 exit status
makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by czxichen** [comment]
Thank you every much.
