### ISSUE TITLE
ubuntu make error

### ISSUE THREAD

**Issue by czxichen** [mattn/go-gtk#243]
pkg-config --cflags gtksourceview-2.0
# pkg-config --cflags gtksourceview-2.0
Package gtksourceview-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtksourceview-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtksourceview-2.0' found
pkg-config: exit status 1
make: *** [all] Error 2

**Comment by mattn** [comment]
```
sudo apt-get install libgtksourceview2.0-dev
```
