### ISSUE TITLE
New pointer checks in Go 1.6

### ISSUE THREAD

**Issue by aliasaila** [mattn/go-gtk#250]
This [commit](https://github.com/golang/go/commit/9dcc58c3d139ee0475fdaca8119812c014ec5ba1) checks pointers passed from Go to C. (See also: [golang/go#12416](https://github.com/golang/go/issues/12416))

An example of the resulting panic:

```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/mattn/go-gtk/gtk._cgoCheckPointer0(0x564a80, 0xc82000e160, 0x0, 0x0, 0x0, 0xc82000a2b4)
	??:0 +0x4d
github.com/mattn/go-gtk/gtk.Init(0x8fcce0)
	src/github.com/mattn/go-gtk/gtk/gtk.go:226 +0x265
```

**Comment by mattn** [comment]
Still not
