### ISSUE TITLE
Panic in gtk.Init()

### ISSUE THREAD

**Issue by zcalusic** [mattn/go-gtk#251]
Applying e2d3968d6ae76b27bb7fe8c0f51c7cb32b76af81 produces this panic:
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/mattn/go-gtk/gtk.Init(0x933ed0)
	/home/zcalusic/src/github.com/mattn/go-gtk/gtk/gtk.go:226 +0x3e3
main.main()
```
gtk.Init() called like this (the first line in main()):

```go
gtk.Init(&os.Args)
```
No arguments passed to application.

go version:
```
go version go1.5.1 linux/amd64
```

**Comment by mattn** [comment]
merge into https://github.com/mattn/go-gtk/issues/263
