### ISSUE TITLE
Cross compile support with cgo?

### ISSUE THREAD

**Issue by dpapathanasiou** [mattn/go-gtk#254]
こんにちは。

I'm trying to cross compile for windows using go version 1.5.2, like this:

```sh
$ GOOS=windows GOARCH=386 CGO_ENABLED=1 go build -o go-one-password-ui go-one-password-ui.go
# runtime/cgo
gcc: error: unrecognized command line option ‘-mthreads’
```

As per the advice from [this thread](http://stackoverflow.com/a/24351448), I have also installed <tt>gcc-multilib</tt> before I tried cross compiling.

Will there be any support for this in the future?

The main reason I'm using go-gtk in my project is that I would like to produce gui applications for multiple operating systems.

**Comment by mattn** [comment]
Are you using cross-compiler for windows?

**Comment by dpapathanasiou** [comment]
明けましておめでとうございます！

I tried both Mac OSX and Windows, and they both failed at "runtime/cgo".

**Comment by mattn** [comment]
Happy New Year.

You need to specify CC to cross-compiler for windows.

**Comment by dpapathanasiou** [comment]
So I do have [mingw](https://wiki.debian.org/Mingw-W64) installed (I'm using debian linux), but when I specify one of the mingw gcc compilers with CC, it complains that pango and glib are not installed:

```sh
$ CC=i686-w64-mingw32-gcc-win32 GOOS=windows GOARCH=386 CGO_ENABLED=1 \
go build -o go-one-password-ui go-one-password-ui.go 
# github.com/mattn/go-gtk/pango
/usr/bin/i686-w64-mingw32-ld: cannot find -lpango-1.0
/usr/bin/i686-w64-mingw32-ld: cannot find -lgobject-2.0
/usr/bin/i686-w64-mingw32-ld: cannot find -lglib-2.0
collect2: error: ld returned 1 exit status
# github.com/mattn/go-gtk/glib
/usr/bin/i686-w64-mingw32-ld: cannot find -lgobject-2.0
/usr/bin/i686-w64-mingw32-ld: cannot find -lglib-2.0
collect2: error: ld returned 1 exit status
```

Just to be sure, I try this, but it tells me it's already installed:

```sh
# apt-get install libpango1.0
libpango1.0-0 is already the newest version.
libpango1.0-dev is already the newest version.
```

So what am I missing?

I looked at the [go build source](https://github.com/golang/go/blob/master/src/cmd/dist/build.go), and also tried the LDFLAGS option, but always with the same result.

How can I tell the mingw compiler where the pango and glib libraries are?

**Comment by mattn** [comment]
```
# apt-get install libpango1.0
libpango1.0-0 is already the newest version.
libpango1.0-dev is already the newest version.
```
it is libraries that is built for host OS not windows. you need to build the libraries for windows.

**Comment by dpapathanasiou** [comment]
So does that mean I need to find a windows machine and install gtk + pango there before I can try cross compiling this?

Debian linux is my main environment, and I thought by installing the https://wiki.debian.org/Mingw-W64 package, it would include what I needed.

I see from looking in <tt>/usr/i686-w64-mingw32</tt>, though, that they're not there...

Is there any guide you could recommend for how to do this? I'm sure other people who use go-gtk will have similar questions.

**Comment by mattn** [comment]
> So does that mean I need to find a windows machine and install gtk + pango there before I can try cross compiling this?

No, you can build the libraries using your cross compiler for windows. At least, what you did show me is not for windows.

```

# apt-get install libpango1.0
libpango1.0-0 is already the newest version.
libpango1.0-dev is already the newest version.
```

**Comment by dpapathanasiou** [comment]
Hmmm... so I admit I'm confused as to how to go about this.

Searching pango for windows gives me installers that won't work on linux.

Similarly, if I search aptitude for pango, all I get is the linux version.

I suppose I need to find the debian version of mingw-pango if such a thing exists (it doesn't seem to).
