### ISSUE TITLE
If I try any of the examples I get this error(OS X 10.11 and GTK+3)

### ISSUE THREAD

**Issue by StaschikT** [mattn/go-gtk#272]
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x4d1d7e2]

runtime stack:
runtime.throw(0x42060e0, 0x2a)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x90
runtime.sigpanic()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4114160, 0xc820049d38, 0x100000000000000)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/cgocall.go:123 +0x11b fp=0xc820049d00 sp=0xc820049cd0
github.com/mattn/go-gtk/gtk._Cfunc_gtk_init(0xc82000a254, 0x51000b0)
	??:0 +0x36 fp=0xc820049d38 sp=0xc820049d00
github.com/mattn/go-gtk/gtk.Init(0x42ea7a0)
	/Users/Tristan_Staschik/Projects/Go/src/github.com/mattn/go-gtk/gtk/gtk.go:230 +0x1ee fp=0xc820049e20 sp=0xc820049d38
main.main()
	/Users/Tristan_Staschik/desktop/main.go:10 +0x32 fp=0xc820049f50 sp=0xc820049e20
runtime.main()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc820049fa0 sp=0xc820049f50
runtime.goexit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820049fa8 sp=0xc820049fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 +0x1

**Comment by mattn** [comment]
I figure out. should be fixed.

**Comment by belak** [comment]
I seem to be running into similar problems on linux:

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x80 addr=0x0 pc=0x7f48dfe8343d]

runtime stack:
runtime.throw(0x76d020, 0x2a)
	/usr/lib/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/lib/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x5dc010, 0xc820049b68, 0x100000000000000)
	/usr/lib/go/src/runtime/cgocall.go:123 +0x11b fp=0xc820049b30 sp=0xc820049b00
github.com/mattn/go-gtk/gtk._Cfunc_gtk_init(0xc82000a2ec, 0xc82000a350)
	??:0 +0x36 fp=0xc820049b68 sp=0xc820049b30
github.com/mattn/go-gtk/gtk.Init(0xb16f50)
	/home/belak/go/src/github.com/mattn/go-gtk/gtk/gtk.go:230 +0x1ff fp=0xc820049c40 sp=0xc820049b68
main.main()
	/home/belak/go/src/github.com/mattn/go-gtk/example/demo/demo.go:49 +0x32 fp=0xc820049f50 sp=0xc820049c40
runtime.main()
	/usr/lib/go/src/runtime/proc.go:188 +0x2b0 fp=0xc820049fa0 sp=0xc820049f50
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820049fa8 sp=0xc820049fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1
```

**Comment by mattn** [comment]
It seems that gtk_init doesn't allow the buffer application allocated. hmm.

**Comment by gamerscomplete** [comment]
Having the same problem running the demo.
amd64 linux

[19:03:14] [chris@monster ~/checkout/src/github.com/mattn/go-gtk]$ ./example/demo/demo 
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x80 addr=0x0 pc=0x7fcf217c555d]

runtime stack:
runtime.throw(0x74ce40, 0x2a)
	/usr/lib/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/usr/lib/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x443c00, 0xc820053b80, 0x0)
	/usr/lib/go/src/runtime/cgocall.go:120 +0x11b fp=0xc820053b50 sp=0xc820053b20
github.com/mattn/go-gtk/gtk._Cfunc_gtk_init(0xc82000a3a0, 0xc82000a3b0)
	??:0 +0x31 fp=0xc820053b80 sp=0xc820053b50
github.com/mattn/go-gtk/gtk.Init(0xaf8aa0)
	/home/chris/checkout/src/github.com/mattn/go-gtk/gtk/gtk.go:230 +0x1a2 fp=0xc820053c40 sp=0xc820053b80
main.main()
	/home/chris/checkout/src/github.com/mattn/go-gtk/example/demo/demo.go:49 +0x32 fp=0xc820053f50 sp=0xc820053c40
runtime.main()
	/usr/lib/go/src/runtime/proc.go:111 +0x2b0 fp=0xc820053fa0 sp=0xc820053f50
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820053fa8 sp=0xc820053fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

**Comment by igarcez** [comment]
also having similar problem
```
./example/demo/demo 
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x80 addr=0x0 pc=0x7efe35b744dd]

runtime stack:
runtime.throw(0x76d020, 0x2a)
	/usr/lib/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/lib/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x5dc010, 0xc82004db68, 0x100000000000000)
	/usr/lib/go/src/runtime/cgocall.go:123 +0x11b fp=0xc82004db30 sp=0xc82004db00
github.com/mattn/go-gtk/gtk._Cfunc_gtk_init(0xc82000a3d4, 0xc82000a3d8)
	??:0 +0x36 fp=0xc82004db68 sp=0xc82004db30
github.com/mattn/go-gtk/gtk.Init(0xb16f30)
	/home/ian/go/src/github.com/mattn/go-gtk/gtk/gtk.go:230 +0x1ff fp=0xc82004dc40 sp=0xc82004db68
main.main()
	/home/ian/tmp/go-gtk/example/demo/demo.go:49 +0x32 fp=0xc82004df50 sp=0xc82004dc40
runtime.main()
	/usr/lib/go/src/runtime/proc.go:188 +0x2b0 fp=0xc82004dfa0 sp=0xc82004df50
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82004dfa8 sp=0xc82004dfa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1
```
archlinux GTK+ 3.20.6

**Comment by mattn** [comment]
This is my TODO. If you want to get workaround, please pass nil into gtk.Init.

**Comment by mattn** [comment]
BTW, go-gtk doesn't provide gtk3 interface. So @igarcez, probably you are not using my package.

**Comment by igarcez** [comment]
@mattn sorry, I also have gtk2 installed, passing nil works, thank you and keep doing a great job.

**Comment by mattn** [comment]
merge into https://github.com/mattn/go-gtk/issues/263
