### ISSUE TITLE
go get github.com/mattn/go-gtk/gtk 

### ISSUE THREAD

**Issue by srinivasumeka123** [mattn/go-gtk#281]
Hi all,
     go get github.com/mattn/go-gtk/gtk
     when i trying to download while got below error, i did't understand !!!
     please help me on this
#########################################
# pkg-config --cflags glib-2.0 gobject-2.0
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
Package gobject-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-2.0' found
pkg-config: exit status 1
# pkg-config --cflags pango
Package pango was not found in the pkg-config search path.
Perhaps you should add the directory containing `pango.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pango' found
pkg-config: exit status 1

**Comment by mattn** [comment]
because you don't install glib/gtk/pango
