### ISSUE TITLE
Highlight selected column

### ISSUE THREAD

**Issue by PiotrKlosek** [mattn/go-gtk#292]
Hi, 
 I'm building csv reader using your libs and I wonder how solve column highlight problem. I was looking for some function to set attributes and I found one(AddAttribute) but this only read attribute from the column and set it to cell. Do you maybe have some other solution for my problem, I would be very pleased. 
Greetings PK

**Comment by mattn** [comment]
What widget do you use? Can you provide code reproduce?

**Comment by PiotrKlosek** [comment]
Sure, this make columns and add text that reads from .csv file. And now I want to highlight column somehow when I click on.


    dw.treeView.column = make([]*gtk.TreeViewColumn, w)
    dw.treeView.cell = make([]*gtk.CellRendererText, w)
    column := gtk.NewTreeViewColumnWithAttributes("#",
      gtk.NewCellRendererText(), "text", 0)
    column.SetClickable(true)
    column.Connect("clicked", func() {
      fmt.Println("All")
    })
       f := func(i int) func() {
         return func() {
           fmt.Println(i)

      }
    }

    dw.treeView.tree.AppendColumn(column)
    if hasHead == false {
      for i := 0; i < w; i++ {
        dw.treeView.cell[i] = gtk.NewCellRendererText()
        dw.treeView.column[i] = gtk.NewTreeViewColumnWithAttributes("empty",
          dw.treeView.cell[i], "text", i+1)

        dw.treeView.column[i].SetClickable(true)
        dw.treeView.column[i].SetReorderable(true)
        dw.treeView.column[i].Connect("clicked", f(i))
        dw.treeView.tree.AppendColumn(dw.treeView.column[i])

      }
    } else {
      sName := dt.GetHeader()
      dw.treeView.tree.SetModel(store)
      for i := range sName {
        dw.treeView.cell[i] = gtk.NewCellRendererText()
        dw.treeView.column[i] = gtk.NewTreeViewColumnWithAttributes(sName[i],
          dw.treeView.cell[i], "text", i+1)

        dw.treeView.column[i].SetClickable(true)
        dw.treeView.column[i].SetReorderable(true)
        dw.treeView.column[i].Connect("clicked", f(i))
        dw.treeView.tree.AppendColumn(dw.treeView.column[i])

      }

    }

    for i := 0; i < h; i++ {

      var iter gtk.TreeIter
      store.Append(&iter)
      record := dt.GetRecord(i)
      count := strconv.Itoa(i + 1)

      record = append([]string{count}, record...)
      for j := 0; j < w+1; j++ {
        store.Set(&iter, j, record[j])

      }
    }

**Comment by mattn** [comment]
You can try following patch on examples/listview.

```diff
diff --git a/example/listview/listview.go b/example/listview/listview.go
index 409d6c2..f16c7dd 100644
--- a/example/listview/listview.go
+++ b/example/listview/listview.go
@@ -17,12 +17,12 @@ func main() {
 
 	swin := gtk.NewScrolledWindow(nil, nil)
 
-	store := gtk.NewListStore(glib.G_TYPE_STRING, glib.G_TYPE_BOOL, gdkpixbuf.GetType())
+	store := gtk.NewListStore(glib.G_TYPE_STRING, glib.G_TYPE_BOOL, gdkpixbuf.GetType(), glib.G_TYPE_STRING)
 	treeview := gtk.NewTreeView()
 	swin.Add(treeview)
 
 	treeview.SetModel(store)
-	treeview.AppendColumn(gtk.NewTreeViewColumnWithAttributes("name", gtk.NewCellRendererText(), "text", 0))
+	treeview.AppendColumn(gtk.NewTreeViewColumnWithAttributes("name", gtk.NewCellRendererText(), "text", 0, "background", 3))
 	treeview.AppendColumn(gtk.NewTreeViewColumnWithAttributes("check", gtk.NewCellRendererToggle(), "active", 1))
 	treeview.AppendColumn(gtk.NewTreeViewColumnWithAttributes("icon", gtk.NewCellRendererPixbuf(), "pixbuf", 2))
 	n := 0
@@ -34,6 +34,7 @@ func main() {
 			0, id,
 			1, (n == 1),
 			2, gtk.NewImage().RenderIcon(id, gtk.ICON_SIZE_SMALL_TOOLBAR, "").GPixbuf,
+			3, "red",
 		)
 		n = 1 - n
 	})
```

**Comment by PiotrKlosek** [comment]
Thanks I also made solution like this, but I think it don't solve my problem. I am doing "excel" for big CSV file. So add additional column with color is not so satisfied. Anyway that's for your reply. Can I ask You a question, when will You finish this gtk lib ?

**Comment by mattn** [comment]
not column. it should be appended into list store. see the diff above. I don't append into column.

**Comment by PiotrKlosek** [comment]
This is how it looks, 

![highlight](https://cloud.githubusercontent.com/assets/22747176/20621762/1131f176-b300-11e6-8550-fb6cebbc0e80.png)

And I don't want additional column.

**Comment by PiotrKlosek** [comment]
Sorry my mistake

**Comment by mattn** [comment]
closable?

**Comment by PiotrKlosek** [comment]
One question, can you give me example, I want to replace old column with new one with background color when i press on column header.

**Comment by mattn** [comment]
okay but if i can take enough time to do. :-o

**Comment by PiotrKlosek** [comment]
Look what I've done, maybye that would help you.

https://gist.github.com/PiotrKlosek/5414aeede32c0517538830d309e049bf#file-reader-go

And now in line 54 I want to change background color of column. But I want to done it without display additional column with color, do you see any solution ?

**Comment by mattn** [comment]
okay. closable?

**Comment by PiotrKlosek** [comment]
Yes, sure
