### ISSUE TITLE
NewDialog appears on wrong screen

### ISSUE THREAD

**Issue by ecc1** [mattn/go-gtk#324]
Here's a simple test program that I expect to pop up a dialog near the main window.  But on my dual-screen setup, it always appears in the center of the left screen, even if the main window is on the right.
I'm pretty sure this used to work -- it's taken from a larger program that I use, and I only recently noticed this behavior, so I suspect it's something in the underlying X environment that's changed.  But I'd still like to fix or work around this behavior somehow.
```
package main

import (
	"github.com/mattn/go-gtk/gtk"
)

func popup() {
	dialog := gtk.NewDialog()
	dialog.SetSizeRequest(100, 50)
	button := gtk.NewButtonWithLabel("Done")
	button.Connect("clicked", gtk.MainQuit)
	dialog.GetVBox().Add(button)
	dialog.ShowAll()
}

func main() {
	gtk.Init(nil)
	window := gtk.NewWindow(gtk.WINDOW_TOPLEVEL)
	window.SetSizeRequest(250, 100)
	window.Connect("destroy", gtk.MainQuit)
	button := gtk.NewButtonWithLabel("Click Me")
	button.Connect("clicked", popup)
	window.Add(button)
	window.ShowAll()
	gtk.Main()
}
```

**Comment by ecc1** [comment]
I found a satisfactory workaround: ```gtk.NewMessageDialog``` with the main window as argument, positions the dialog nearby.

**Comment by mattn** [comment]
did you try SetTransientFor?

**Comment by ecc1** [comment]
This also solves the problem.  Still curious why it used to work; I guess I was relying on some underlying window manager behavior that wasn't guaranteed.  Closing this issue, thanks.
