### ISSUE TITLE
Cross Compilation to RaspberryPi

### ISSUE THREAD

**Issue by minhajakhterkhan199** [mattn/go-gtk#326]
I am using GO-GTK to display images, the project is working fine on amd64 but when I try to cross compile it for arm (RaspberryPi), it gives me below error. 
Please advise how to cross-compile go-gtk from amd64 to arm (Raspberrypi3). 

github.com/mattn/go-gtk/glib
# github.com/mattn/go-gtk/glib
In file included from /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:9:0,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from ./glib.go.h:4,
                 from src/github.com/mattn/go-gtk/glib/glib.go:5:
/usr/include/glib-2.0/glib/gtypes.h: In function '_GLIB_CHECKED_ADD_U64':
/usr/include/glib-2.0/glib/gmacros.h:232:53: error: size of array '_GStaticAssertCompileTimeAssertion_0' is negative
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                                     ^
/usr/include/glib-2.0/glib/gmacros.h:229:47: note: in definition of macro 'G_PASTE_ARGS'
 #define G_PASTE_ARGS(identifier1,identifier2) identifier1 ## identifier2
                                               ^
/usr/include/glib-2.0/glib/gmacros.h:232:44: note: in expansion of macro 'G_PASTE'
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                            ^
/usr/include/glib-2.0/glib/gtypes.h:422:3: note: in expansion of macro 'G_STATIC_ASSERT'
   G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
   ^
github.com/mattn/go-gtk/pango
# github.com/mattn/go-gtk/pango
In file included from /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:9:0,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/pango-1.0/pango/pango-coverage.h:25,
                 from /usr/include/pango-1.0/pango/pango-font.h:25,
                 from /usr/include/pango-1.0/pango/pango-attributes.h:25,
                 from /usr/include/pango-1.0/pango/pango.h:25,
                 from ./pango.go.h:7,
                 from src/github.com/mattn/go-gtk/pango/pango.go:5:
/usr/include/glib-2.0/glib/gtypes.h: In function '_GLIB_CHECKED_ADD_U64':
/usr/include/glib-2.0/glib/gmacros.h:232:53: error: size of array '_GStaticAssertCompileTimeAssertion_0' is negative
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                                     ^
/usr/include/glib-2.0/glib/gmacros.h:229:47: note: in definition of macro 'G_PASTE_ARGS'
 #define G_PASTE_ARGS(identifier1,identifier2) identifier1 ## identifier2
                                               ^
/usr/include/glib-2.0/glib/gmacros.h:232:44: note: in expansion of macro 'G_PASTE'
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                            ^
/usr/include/glib-2.0/glib/gtypes.h:422:3: note: in expansion of macro 'G_STATIC_ASSERT'
   G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));

----------------------------------------------------------
go env
------------------------------------------------------------
GOARCH="arm"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/minhaj/GoLang"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
GOARM=""
CC="arm-linux-gnueabi-gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build472526669=/tmp/go-build -gno-record-gcc-switches"
CXX="arm-linux-gnueabi-g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

**Comment by mattn** [comment]
Are you using Cross-C-Compiler?

**Comment by minhajakhterkhan199** [comment]
I am using 'go build -v IndoorMass/' and set 'CC=arm-linux-gnueabi-gcc' with cgo enabled. 
arm-linux-gnueabi-gcc is C-Cross-Compiler

**Comment by mattn** [comment]
As far as I read your build log, it seems that you're trying to compile it with 32bit target.

>/usr/include/glib-2.0/glib/gtypes.h: In function '_GLIB_CHECKED_ADD_U64':
/usr/include/glib-2.0/glib/gmacros.h:232:53: error: size of array '_GStaticAssertCompileTimeAssertion_0' is negative

This can be your help? https://stackoverflow.com/questions/37935605/32-bit-compilation-failing-on-64-bit-ubuntu-16-04

**Comment by minhajakhterkhan199** [comment]
Dear, 
Please advise to solve the issue, I do not got anything from your recommended link... 
Please clarify how to solve the issue.

**Comment by mattn** [comment]
I guess that you miss that target architecture. for example, using 32bit compiler for 64bit OS.

**Comment by minhajakhterkhan199** [comment]
I set CC_FOR_TARGET=arm-linux-gnueabi-gcc but still I have same error. 
Kindly advise to solve the issue.

**Comment by mattn** [comment]
As far as I can see this log

>G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));

You have problem about compiler.

**Comment by minhajakhterkhan199** [comment]
Dear, 
Please advise specifically how to solve the compiler problem... Should I have to use ARCH64 compiler?

**Comment by mattn** [comment]
Since I dont know your environment, I cannot,

On 5/28/17, minhajakhterkhan199 <notifications@github.com> wrote:
> Dear,
> Please advise specifically how to solve the compiler problem... Should I
> have to use ARCH64 compiler?
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/mattn/go-gtk/issues/326#issuecomment-304467643


-- 
- Yasuhiro Matsumoto

**Comment by minhajakhterkhan199** [comment]
Dear,
I already given my go environment variables, what other environment variables you need... Please advise I will also provide you that environment variables... 
In this regards, waiting for your response.

**Comment by minhajakhterkhan199** [comment]
Waiting for your response

**Comment by mattn** [comment]
Are you trying to build it for 32bit RaspberryPi on 64bit OS?

**Comment by minhajakhterkhan199** [comment]
I am trying building it for 32bit Raspberry Pi, without GTK I am able to compile & run it on Raspberry pi3.
Please advise to solve the issue
-------------------------------------------------------------------------
file IndoorMass 
IndoorMass: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=099127fa242ff1304a8b81331e297312569c553b, not stripped
--------------------------------------------------------------------------

**Comment by mattn** [comment]
Maybe, you installed 64bit libraries of gtk. You need to install or build 32bit libraries for the target.

**Comment by minhajakhterkhan199** [comment]
I have installed & reinstalled gtk using below commands. Please advise
go get github.com/mattn/go-gtk/gtk

sudo apt-get install libgtk2.0-dev libglib2.0-dev libgtksourceview2.0-dev

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  bridge-utils containerd libcaca-dev libepoxy-dev libfribidi-dev
  libglu1-mesa-dev libgmp-dev libgmpxx4ldbl libjpeg-turbo8-dev libsdl1.2debian
  libslang2-dev linux-headers-4.4.0-64 linux-headers-4.4.0-64-generic
  linux-headers-4.4.0-66 linux-headers-4.4.0-66-generic linux-headers-4.4.0-67
  linux-headers-4.4.0-67-generic linux-headers-4.4.0-70
  linux-headers-4.4.0-70-generic linux-headers-4.4.0-71
  linux-headers-4.4.0-71-generic linux-headers-4.4.0-72
  linux-headers-4.4.0-72-generic linux-image-4.4.0-64-generic
  linux-image-4.4.0-66-generic linux-image-4.4.0-67-generic
  linux-image-4.4.0-70-generic linux-image-4.4.0-71-generic
  linux-image-4.4.0-72-generic linux-image-extra-4.4.0-64-generic
  linux-image-extra-4.4.0-66-generic linux-image-extra-4.4.0-67-generic
  linux-image-extra-4.4.0-70-generic linux-image-extra-4.4.0-71-generic
  linux-image-extra-4.4.0-72-generic nettle-dev runc ubuntu-fan
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libatk1.0-dev libcairo2-dev libgdk-pixbuf2.0-dev libpango1.0-dev
Suggested packages:
  libcairo2-doc libglib2.0-doc libgtk2.0-doc libgtksourceview2.0-doc
  libpango1.0-doc
The following NEW packages will be installed:
  libatk1.0-dev libcairo2-dev libgdk-pixbuf2.0-dev libglib2.0-dev
  libgtk2.0-dev libgtksourceview2.0-dev libpango1.0-dev
0 upgraded, 7 newly installed, 0 to remove and 80 not upgraded.
Need to get 0 B/5,133 kB of archives.
After this operation, 35.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Selecting previously unselected package libglib2.0-dev.
(Reading database ... 449629 files and directories currently installed.)
Preparing to unpack .../libglib2.0-dev_2.48.2-0ubuntu1_amd64.deb ...
Unpacking libglib2.0-dev (2.48.2-0ubuntu1) ...
Selecting previously unselected package libatk1.0-dev.
Preparing to unpack .../libatk1.0-dev_2.18.0-1_amd64.deb ...
Unpacking libatk1.0-dev (2.18.0-1) ...
Selecting previously unselected package libcairo2-dev.
Preparing to unpack .../libcairo2-dev_1.14.6-1_amd64.deb ...
Unpacking libcairo2-dev (1.14.6-1) ...
Selecting previously unselected package libgdk-pixbuf2.0-dev.
Preparing to unpack .../libgdk-pixbuf2.0-dev_2.32.2-1ubuntu1.2_amd64.deb ...
Unpacking libgdk-pixbuf2.0-dev (2.32.2-1ubuntu1.2) ...
Selecting previously unselected package libpango1.0-dev.
Preparing to unpack .../libpango1.0-dev_1.38.1-1_amd64.deb ...
Unpacking libpango1.0-dev (1.38.1-1) ...
Selecting previously unselected package libgtk2.0-dev.
Preparing to unpack .../libgtk2.0-dev_2.24.30-1ubuntu1_amd64.deb ...
Unpacking libgtk2.0-dev (2.24.30-1ubuntu1) ...
Selecting previously unselected package libgtksourceview2.0-dev.
Preparing to unpack .../libgtksourceview2.0-dev_2.10.5-2ubuntu2_amd64.deb ...
Unpacking libgtksourceview2.0-dev (2.10.5-2ubuntu2) ...
Processing triggers for libglib2.0-0:amd64 (2.48.2-0ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up libglib2.0-dev (2.48.2-0ubuntu1) ...
Setting up libatk1.0-dev (2.18.0-1) ...
Setting up libcairo2-dev (1.14.6-1) ...
Setting up libgdk-pixbuf2.0-dev (2.32.2-1ubuntu1.2) ...
Setting up libpango1.0-dev (1.38.1-1) ...
Setting up libgtk2.0-dev (2.24.30-1ubuntu1) ...
Setting up libgtksourceview2.0-dev (2.10.5-2ubuntu2) ...

**Comment by mattn** [comment]
> sudo apt-get install libgtk2.0-dev libglib2.0-dev libgtksourceview2.0-dev

You typed this on 64bit OS. You must install 32bit libraries. If you don't find it, you must compile it from source.

**Comment by minhajakhterkhan199** [comment]
After adding 32bit libraries, I am getting below error messages. Please advise to fix the issue
github.com/mattn/go-gtk/glib
# pkg-config --cflags glib-2.0 gobject-2.0
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
Package gobject-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-2.0' found
pkg-config: exit status 1
github.com/mattn/go-gtk/pango
# pkg-config --cflags pango
Package pango was not found in the pkg-config search path.
Perhaps you should add the directory containing `pango.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pango' found
pkg-config: exit status 1

**Comment by minhajakhterkhan199** [comment]
Dear, 
After doing everything I can, now I am getting below error, Please advise to solve the issue during cross compilation. 

github.com/mattn/go-gtk/glib
# github.com/mattn/go-gtk/glib
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lgobject-2.0
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lglib-2.0
collect2: error: ld returned 1 exit status
github.com/mattn/go-gtk/pango
# github.com/mattn/go-gtk/pango
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lpango-1.0
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lgobject-2.0
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: cannot find -lglib-2.0
collect2: error: ld returned 1 exit status

**Comment by minhajakhterkhan199** [comment]
thanks issue fixed!

**Comment by mattn** [comment]
Good to hear. 👍

**Comment by taraninomula** [comment]
> thanks issue fixed!
Hi i am also facing the same errors when i am trying to cross compile gstreamer code for raspberrypi. Can you please explain me how this issue was fixed.These are the errors i am facing

/usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lgstvideo-1.0
/usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lgstbase-1.0
/usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lgtk-3
/usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lgdk-3
/usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/../../../../arm-linux-gnueabihf/bin/ld: cannot find -latk-1.0
/usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lgio-2.0
/usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lpangocairo-1.0
/usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lgdk_pixbuf-2.0
/usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lcairo-gobject
/usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lpango-1.0
/usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lcairo
/usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lgstreamer-1.0
/usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lgobject-2.0
/usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lglib-2.0
collect2: error: ld returned 1 exit status

**Comment by mattn** [comment]
Because you are trying to link gtk3 instead of gtk2. go-gtk use gtk2.
