### ISSUE TITLE
Gtk-WARNING **: cannot open display: 

### ISSUE THREAD

**Issue by minhajakhterkhan199** [mattn/go-gtk#328]
My RaspberryPi application is trying to display images from command line but it is displaying error.
**Gtk-WARNING **: cannot open display:** 

Please advise how can I display images from Command line.

**Comment by mattn** [comment]
please set $DISPLAY environment variable

**Comment by minhajakhterkhan199** [comment]
I am connected to RaspberryPi through SSH and Screen is connected to RaspberryPi. I am running my program from SSH and want it to display on screen connected with Raspberry Pi. 
After using set $DISPLAY still have same error

**Comment by mattn** [comment]
do ssh with `-Y` parameter.

**Comment by minhajakhterkhan199** [comment]
ssh with -Y parameter it shows display on my screen.. I want display on screen connected with Raspberry Pi

**Comment by minhajakhterkhan199** [comment]
waiting for your response.

**Comment by mattn** [comment]
When you need to install X server on Raspberry Pi.

**Comment by minhajakhterkhan199** [comment]
Thanks Issue solved
