### ISSUE TITLE
Unable to launch a go-gtk program on linux

### ISSUE THREAD

**Issue by Litarvan** [mattn/go-gtk#337]
I managed to compile my go-gtk app on windows. But when running on another computer, or without Msys64 in the PATH, Windows can't find the GTK libraries.

Can't i bundle them in the .exe ?
I saw that : https://github.com/mattn/go-gtk/issues/220
But he closed the issue without solving his problem

**Comment by larsth** [comment]
You can't bundle *.dll's into a program. The dynamic linker loads the *.dll's just before it starts the program.

I have no specific knowledge about of how Windows works regarding dynamic linked libraries (dll), but what you need to do is to make sure the dynamic linker can find the *.dll libraries your program are using.

Read this:
https://linux.die.net/man/8/ld-linux
On Linux distros you *could* fiddle with LD_LIBRARY_PATH, if the *.so file (the Linux equiv of a *.dll file) are outside the normal directories that are searched by the dynamic linker.

About Static, Shared Dynamic and Loadable Linux Libraries: 
http://www.yolinux.com/TUTORIALS/LibraryArchives-StaticAndDynamic.html
That is of course specific for Linux distros, but Windows work the same way, but with a slightly different way of doing things.

**Comment by Litarvan** [comment]
Thanks i lot, i will look at this
