### ISSUE TITLE
Window.getsize should return size directly

### ISSUE THREAD

**Issue by lidaobing** [mattn/go-gtk#355]
https://github.com/mattn/go-gtk/blob/2d9b918c84fca8f12b4ed572cd8e8d1f4cb046f5/gtk/gtk.go#L1592

**Comment by mattn** [comment]
Yes, this API was created in oldest to imitate GTK, And I regret about this.

**Comment by mattn** [comment]
If it will provide way to return the size, it should be new func name like Size().

**Comment by lidaobing** [comment]
@mattn I prefer still use `GetSize` and don't keep the compability, because go-gtk still not release 1.0.0, and when 1.0.0 released, it should be `GetSize`
