### ISSUE TITLE
experiencing errors compiling

### ISSUE THREAD

**Issue by blavkboy** [mattn/go-gtk#371]
When I run the command "make example" I get the following output:

cd example/action && go build -x
WORK=C:\Users\MALL@R~1\AppData\Local\Temp\go-build607919654
mkdir -p $WORK\b030\
cd C:\Users\mall@reds\go\src\github.com\mattn\go-gtk\gdk
pkg-config --cflags -- gdk-2.0 gthread-2.0
pkg-config --libs -- gdk-2.0 gthread-2.0
go build github.com/mattn/go-gtk/gdk: invalid flag in pkg-config --libs: -Wl,-luuid
make: *** [example/example.mk:35: example/action/action] Error 1

**Comment by mattn** [comment]
see https://github.com/golang/go/issues/23749
