### ISSUE TITLE
Cannot make example as stated in README.md

### ISSUE THREAD

**Issue by sfkrystal** [mattn/go-gtk#390]
**System:**

	Ubuntu LTS 18.04
	libcairo2-dev is already the newest version (1.15.10-2).
	libcairo2-dev set to manually installed.
	libgtk-3-dev is already the newest version (3.22.30-1ubuntu1).
	libglib2.0-dev is already the newest version (2.56.3-0ubuntu0.18.04.1).
	libglib2.0-dev set to manually installed.
	libgtksourceview2.0-dev is already the newest version (2.10.5-3).

**From README.md:**

	You can experiment with go-gtk by running the various example programs:
	
	git clone https://github.com/mattn/go-gtk
	cd go-gtk
	make example
	./example/demo/demo

**Tried:** as stated in README (already had mattn folder for sqlite - _**thanks btw!**_):

	krystal@WALLE:~/go/src/github.com/mattn$ git clone https://github.com/mattn/go-gtk
	krystal@WALLE:~/go/src/github.com/mattn/go-gtk$ make example
	make: *** No rule to make target 'example/action/action.go', needed by 'example/action/action'.  Stop.

**Tried:** solution in issue #31

	krystal@WALLE:~/go/src/github.com/mattn/go-gtk$ make clean
	rm -f _example/action/action _example/alignment/alignment _example/builder/builder _example/clipboard/clipboard _example/demo/demo _example/arrow/arrow _example/dnd/dnd _example/drawable/drawable _example/event/event _example/expander/expander _example/iconview/iconview _example/listview/listview _example/locale/locale _example/notebook/notebook _example/number/number _example/sourceview/sourceview _example/spinbutton/spinbutton _example/statusicon/statusicon _example/table/table _example/thread/thread _example/toolbar/toolbar _example/treeview/treeview _example/twitterstream/twitterstream
	krystal@WALLE:~/go/src/github.com/mattn/go-gtk$ make install
	make: *** No rule to make target 'install'.  Stop.

**Tried:** renaming "_example" to "example":

	krystal@WALLE:~/go/src/github.com/mattn/go-gtk$ mv _example/ example
	krystal@WALLE:~/go/src/github.com/mattn/go-gtk$ make example
	Makefile:1: _example/example.mk: No such file or directory
	make: *** No rule to make target '_example/example.mk'.  Stop.

**Tried:** find/replace "example/" with "_example/" in _example/example.mk:

	krystal@WALLE:~/go/src/github.com/mattn/go-gtk$ make example 
	cd _example/action && go build -x
	WORK=/tmp/go-build376418325
	../../gtk/gtk.go:24:2: cannot find package "github.com/mattn/go-pointer" in any of:
		/usr/lib/go-1.10/src/github.com/mattn/go-pointer (from $GOROOT)
		/home/krystal/go/src/github.com/mattn/go-pointer (from $GOPATH)
	_example/example.mk:35: recipe for target '_example/action/action' failed
	make: *** [_example/action/action] Error 1

**Tried:** comment out import in got-gtk/gtk/gtk.go:

make goes _much_ further, but (obviously) ends with:
	
	[...]
	/usr/lib/go-1.10/pkg/tool/linux_amd64/compile -o $WORK/b025/_pkg_.a -trimpath $WORK/b025 -p github.com/mattn/go-gtk/gtk -buildid M6YGwZ5ziEXFCzRVWWPG/M6YGwZ5ziEXFCzRVWWPG -goversion go1.10.4 -D "" -importcfg $WORK/b025/importcfg -pack -c=4 $WORK/b025/_cgo_gotypes.go $WORK/b025/gtk.cgo1.go $WORK/b025/_cgo_import.go
	# github.com/mattn/go-gtk/gtk
	../../gtk/gtk.go:4854: undefined: pointer in pointer.Restore
	[...]
	../../gtk/gtk.go:11412: undefined: pointer in pointer.Restore
	_example/example.mk:35: recipe for target '_example/action/action' failed
	make: *** [_example/action/action] Error 2

See attached for full text of this.

[gogtk make output.txt](https://github.com/mattn/go-gtk/files/2588573/gogtk.make.output.txt)

**Comment by mattn** [comment]
Once, please do make on root directory of repository.

**Comment by sfkrystal** [comment]
Thank you for your quick response (and your packages!)

I did first try the directions in README.md:

```
krystal@WALLE:~/go/src/github.com/mattn$ git clone https://github.com/mattn/go-gtk
Cloning into 'go-gtk'...
remote: Enumerating objects: 5056, done.
remote: Total 5056 (delta 0), reused 0 (delta 0), pack-reused 5056
Receiving objects: 100% (5056/5056), 2.43 MiB | 3.14 MiB/s, done.
Resolving deltas: 100% (2286/2286), done.
krystal@WALLE:~/go/src/github.com/mattn$ ls
go-gtk  go-sqlite3
krystal@WALLE:~/go/src/github.com/mattn$ cd go-gtk/
krystal@WALLE:~/go/src/github.com/mattn/go-gtk$ ls
data      gdk        gio   Gopkg.lock  gtk    gtksourceview  Makefile  README.md  tools
_example  gdkpixbuf  glib  Gopkg.toml  gtkgl  gtkspell       pango     TODO
krystal@WALLE:~/go/src/github.com/mattn/go-gtk$ make example
make: *** No rule to make target 'example/action/action.go', needed by 'example/action/action'.  Stop.
```

**Comment by sfkrystal** [comment]
This works:
```
go get github.com/mattn/go-gtk/gtk
go get github.com/garyburd/go-oauth/oauth
sed -i 's/example\//_example\//g' _example/example.mk
```
