### ISSUE TITLE
Windows issue

### ISSUE THREAD

**Issue by RuochengShan** [mattn/go-gtk#410]
I have installed gtk+-2.0 using mysy2.
But got a build error like this:
![image](https://user-images.githubusercontent.com/48625024/69455743-0b2bbe80-0d37-11ea-845c-6840c5e4fca8.png)
go version is 1.13.4/amd64
Any help here?

**Comment by mattn** [comment]
See https://github.com/golang/go/wiki/InvalidFlag

You must specify flags to CGO_LDFLAGS_ALLOW.
